GET https://pure-anchorage-70580.herokuapp.com/pkhdbbash52471

###

GET https://pure-anchorage-70580.herokuapp.com/pkhdbbash52471

###

POST https://pure-anchorage-70580.herokuapp.com/pkhdbbash52471
Content-Type: application/json

{
    "name" : "An Amazing Guy Called Guy",
    "subToChannel": "Web Dev Simplified"
}

###

DELETE https://pure-anchorage-70580.herokuapp.com/pkhdbbash52471/5f64b0c02e521a05d0c2ad8b