GET http://localhost:3000/pkhdbbash52471

###

GET http://localhost:3000/pkhdbbash52471/5f649c739431f1269025f912

###

POST http://localhost:3000/pkhdbbash52471
Content-Type: application/json

{
    "name" : "Manit Amazing Guy Called Guy",
    "subToChannel": "Web Dev Simplified"
}