GET https://rest-apiy.herokuapp.com/pkhdbbash52471

###

GET https://rest-apiy.herokuapp.com/pkhdbbash52471/5f649c739431f1269025f912

###

POST https://rest-apiy.herokuapp.com/pkhdbbash52471
Content-Type: application/json

{
    "name" : "An Amazing Guy Called Guy",
    "subToChannel": "Web Dev Simplified"
}

###

DELETE https://rest-apiy.herokuapp.com/pkhdbbash52471/5f64b0c02e521a05d0c2ad8b